# Generated by Django 5.2.18 on 2026-10-09 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_captainprofile_captaindocument_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='captaindocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_captain_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='captainprofile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='captainprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='captainprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_captain_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
