# Generated by Django 5.2.18 on 2026-10-09 03:15

import accounts.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_captaindocument_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captaindocument',
            name='file',
            field=models.FileField(storage=accounts.storage.CaptainDocumentStorage(), upload_to=''),
        ),
    ]
