# Generated by Django 5.2.18 on 2026-10-09 02:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_captainprofile_captaindocument_customerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('SCOOTER', 'Scooter'), ('MOTORCYCLE', 'Motorcycle')], max_length=12)),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('manufacture_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2027)])),
                ('plate_number', models.CharField(max_length=30, unique=True)),
                ('chassis_number', models.CharField(max_length=100, unique=True)),
                ('front_photo', models.ImageField(upload_to='vehicles/front/')),
                ('rear_photo', models.ImageField(upload_to='vehicles/rear/')),
                ('side_photo', models.ImageField(upload_to='vehicles/side/')),
                ('plate_photo', models.ImageField(upload_to='vehicles/plate/')),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='accounts.captainprofile')),
            ],
        ),
    ]
